### PR TITLE
Support temporary (302) redirects

### PR DESCRIPTION
**Pull request by Aupajo**
With no explicit cache expiry set, a browser may choose to cache a 301 redirect for as long as it likes. This can cause problems if you choose to alter where a domain redirects to in the future; browsers which cache the request will continue to point to the old redirect.

By specifying the `temporary` option, a user can ask that `Rack::CanonicalHost` return 302 redirects instead, causing the browser not to cache the request, and making it easier to redirect the domain somewhere else at a later date.

Usage:

```ruby
use Rack::CanonicalHost, 'example.com', temporary: true
```

### CODE REVIEW

**Comment by Aupajo** [comment]
Have updated this PR to display the correct HTML response.

**Comment by Aupajo** [comment]
@tylerhunt Does this look okay?

**Comment by tylerhunt** [comment]
@Aupajo I've been mulling this over, and I'm hesitant to merge it, because it adds additional and unnecessary complexity and isn't really in alignment with the intention of this gem, which is to redirect to the _canonical_ host. For more generic redirects there are other Rack middleware gems out there, like `rack-rewrite`.

Also, it sounds like your primary motivation here is to work around browser caching of permanent redirects, but the new `:cache_control` option should solve that concern, no?

**Comment by Aupajo** [comment]
@tylerhunt That's right, my main motivation is to avoid browser caching. I understand where you're coming from – “canonical” and “temporary” don't really jive. Happy if you want to close this. Thanks for the consideration and the response!

**Pull request closed without merging**
